language: python

python: 3.6

dist: trusty

cache:
  pip: true

install:
  - pip install . --upgrade
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - make test
